[base]
pidfile = "/tmp/comet.pid"
serverId = 1
certPath = ""
keyPath = ""


[websocket]
bind = "0.0.0.0:8911"

[zookeeper]
host = "127.0.0.1:2181"
basePath = "/im_logic_rpc_server"
serverPathLogic = "LogicRpc"
serverPathComet = "CometRpc"
ServerId = "1"

[[rpcLogicAddrs]]
key = 1
addr = "tcp@0.0.0.0:6912"




[bucket]

num = 4
channel = 1024
room = 1024
svrProto = 80
routineAmount = 32
routineSize = 20




